version: 2.1

orbs:
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.3

jobs:
  build-and-test:
    working_directory: ~/django_mri
    docker:
      - image: themattrix/tox
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
          DB_NAME: circle_test
          DB_USER: root
          DB_PASSWORD: password
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Upgrade pip
          command: pip install --upgrade pip setuptools wheel
      - python/install-deps
      - python/save-cache
      - run: pip install tox
      - run:
          name: Test using tox
          command: tox
      - codecov/upload:
          file: coverage.xml
          flags: unittests

workflows:
  main:
    jobs:
      - build-and-test
